apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-ingress-dev
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-ingress
    app.kubernetes.io/component: addon
    app.kubernetes.io/part-of: exchange-settlement
    environment: dev
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: exchange-settlement-dev
  source:
    repoURL: https://github.com/play-builder/argocd-gitops.git
    targetRevision: main
    path: argocd/manifests/dev/argocd-ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 2m
