apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: exchange-settlement-base

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - clustersecretstore.yaml
  - externalsecret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - networkpolicy.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: exchange-settlement
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false

images:
  - name: app
    newName: app
    newTag: latest
